// Cookie Chain configuration constants
// See THESIS.md and CLAUDE.md for context.

import { Commitment } from '@solana/web3.js';

/** Cookie Chain RPC endpoint. */
export const COOKIE_CHAIN_RPC = 'https://rpc.cookiescan.io';

/** Commitment level for tx confirmation. "confirmed" is the sweet spot for game UX. */
export const COOKIE_CHAIN_COMMITMENT: Commitment = 'confirmed';

/**
 * Treasury wallet that receives click burns and dispenses golden-cookie airdrops.
 *
 * Generated by `node app/scripts/generate-treasury.mjs` on 2026-09-07.
 * The corresponding secret key is in `app/scripts/treasury.json` (gitignored).
 * Backup: store `treasury.json` in 1Password or another secure location.
 */
export const TREASURY_PUBKEY = '5Nhcsv4ip2dF5fyN6of3NR98pv3wq75tWdPgqi9iDf29';

/** Lamports burned per click (1 COOK = 1_000_000_000 lamports). 1000 = 0.000001 COOK. */
export const CLICK_BURN_LAMPORTS = 1000;

/** Lamports airdropped on a Golden Cookie hit. 100_000 = 0.0001 COOK. */
export const GOLDEN_COOKIE_LAMPORTS = 100_000;

/** Probability (0..1) of a Golden Cookie on any given click. */
export const GOLDEN_COOKIE_CHANCE = 0.005; // 0.5%

/** CookieScan API base (for future leaderboard/analytics indexing). */
export const COOKIE_SCAN_API = 'https://api.cookiescan.io';

/** Cookie Clicker version tag embedded in memos. */
export const MEMO_TAG = 'click-the-cookie:v1';
